<a href="https://colab.research.google.com/github/fjmsouza/ML2DL/blob/main/dl_az_iris_simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from math import ceil
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils

base = pd.read_csv('iris.csv')
n_atributes = 4
n_classes = 3
n_inputs_neurons = ceil((n_atributes+n_classes)/2)

#split:
previsores = base.iloc[:,0:n_atributes].values
classe = base.iloc[:,n_atributes].values

#de string para numérico
labelencoder = LabelEncoder()
classe = labelencoder.fit_transform(classe)
#iris setosa      1
#iris versicolor  2
#iris virginica   3

#de numerico para ohe(array)
classe_dummy = np_utils.to_categorical(classe)
#iris setosa      100
#iris versicolor  010
#iris virginica   001 

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe_dummy, test_size=0.25)

classificador = Sequential()
#neurons = (4 atributos + 3 classes )/2
classificador.add(Dense(units=n_inputs_neurons, activation='relu', input_dim=n_atributes))
classificador.add(Dense(units=n_inputs_neurons, activation='relu'))
classificador.add(Dense(units=n_classes, activation='softmax'))
classificador.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['categorical_accuracy'])


In [2]:
classificador.fit(previsores_treinamento, classe_treinamento, batch_size=10, epochs=1000)

Epoch 1/1000
12/12 [==============================] - 2s 3ms/step - loss: 2.5993 - categorical_accuracy: 0.3482
Epoch 2/1000
12/12 [==============================] - 0s 3ms/step - loss: 2.3359 - categorical_accuracy: 0.3482
Epoch 3/1000
12/12 [==============================] - 0s 3ms/step - loss: 2.1231 - categorical_accuracy: 0.3482
Epoch 4/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.9545 - categorical_accuracy: 0.3482
Epoch 5/1000
12/12 [==============================] - 0s 2ms/step - loss: 1.8060 - categorical_accuracy: 0.3482
Epoch 6/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.6731 - categorical_accuracy: 0.3482
Epoch 7/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.5582 - categorical_accuracy: 0.3482
Epoch 8/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.4552 - categorical_accuracy: 0.3482
Epoch 9/1000
12/12 [==============================] - 0s 3ms/step - loss: 1.3584 - categorical_accuracy:

In [3]:
resultado = classificador.evaluate(previsores_teste,classe_teste)

2/2 [==============================] - 0s 6ms/step - loss: 0.0223 - categorical_accuracy: 1.0000


In [4]:
previsoes = classificador.predict(previsores_teste)

2/2 [==============================] - 0s 5ms/step


In [7]:
iris1 = np.array([[5.1,3.5,1.4,0.2]])#setosa
iris2 = np.array([[4.9,3.0,1.4,0.2]])#setosa
iris3 = np.array([[5.6,3.0,4.1,1.3]])#versicolor
iris4 = np.array([[5.7,3.0,4.2,1.2]])#versicolor
iris5 = np.array([[6.7,3.3,5.7,2.5]])#virginica
iris6 = np.array([[4.9,2.5,4.5,1.7]])#virginica


previsao1 = classificador.predict(iris1)
previsao2 = classificador.predict(iris2)
previsao3 = classificador.predict(iris3)
previsao4 = classificador.predict(iris4)
previsao5 = classificador.predict(iris5)
previsao6 = classificador.predict(iris6)

print(previsao1)
print(previsao2)
print(previsao3)
print(previsao4)
print(previsao5)
print(previsao6)

1/1 [==============================] - 0s 15ms/step
[[9.9999344e-01 6.4974720e-06 4.7890965e-24]]
[[9.9997783e-01 2.2163113e-05 9.2016280e-22]]
[[9.6129006e-06 9.9974626e-01 2.4409474e-04]]
[[1.8503197e-05 9.9987388e-01 1.0767668e-04]]
[[5.3096769e-16 3.5219677e-04 9.9964786e-01]]
[[1.8904298e-11 5.4141255e-03 9.9458587e-01]]


In [8]:
previsoes = (previsoes > 0.5)
import numpy as np
classe_teste2 = [np.argmax(t) for t in classe_teste]
previsoes2 = [np.argmax(t) for t in previsoes]

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(previsoes2, classe_teste2)

print(matriz)

[[13  0  0]
 [ 0 11  0]
 [ 0  0 14]]
